spring.application.name=cv-intelligence-mcp-server

server.port=9557

spring.datasource.url=jdbc:mysql://localhost:3306/cv-intelligence?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=false
logging.level.org.hibernate=OFF

logging.file.name=log/app.log
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=cv-intelligence
spring.ai.mcp.server.version=1.0.0

spring.main.web-application-type=none
spring.main.banner-mode=off


logging.pattern.console=
